---
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v3
      if: env.month != 'Oct'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for your first issue! ğŸ˜ŠğŸ•¹ï¸'
        pr-message: 'Thank you for contributing to this project! ğŸ˜ŠğŸ•¹ï¸'
    - uses: actions/first-interaction@v3
      if: env.month == 'Oct'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for your first issue! Happy Hacktoberfest!!! ğŸƒğŸ‘•ğŸ•¹ï¸'
        pr-message: 'Thank you for contributing to this project. Happy Hacktoberfest!!! ğŸƒğŸ‘•ğŸ•¹ï¸'
